admin_pizza/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('menu/', include('pizza_website.urls')),
    path('api/', include('pizza_website.api_urls')),
    path('', include('main.urls'))

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # to check doc about the urlpatterns +=static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.index, name="index"),
]

pizza_website/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'menu'
urlpatterns = [
    path('', views.index, name="index"),
]

main/models.py
from django.db import models

# Create your models here.

pizza_website/models.py
from django.db import models

# Create your models here.

class Pizza(models.Model):
    nom = models.CharField(max_length=200)
    ingredient = models.CharField(max_length=400)
    prix = models.FloatField(default=0)
    vegetarienne = models.BooleanField(default=False)

    class Meta:
        db_table = 'pizza_website_pizza'
        managed = False

    def __str__(self):
        return self.nom

main/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    template_name="main/index.html"
    context={}
    return render(request, template_name, context)

pizza_website/views.py
from django.shortcuts import render
from .models import Pizza
from django.http import HttpResponse
from django.core import serializers
# Create your views here.

def index(request):
    pizzas = Pizza.objects.all().order_by('prix')
    context = {'pizza': pizzas}
    return render(request, "menu/index.html", context)

def api_get_pizzas(request):
    pizzas = Pizza.objects.all().order_by('prix')
    json = serializers.serialize('json', pizzas)
    return HttpResponse(json)

main/templates/main/index.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Pizza Mama</title>
    <link rel="stylesheet" href="{% static 'main/style.css' %}">
</head>
<body>
<div class="centered">
<img src= "{% static 'main/images/main_logo.png' %}">
    <a href="{% url 'menu:index' %}">Pizza Menu</a>
</div>
</body>
</html>

templates/menu/index.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Menu Pizza</title>
    <link rel="stylesheet" href="{% static 'menu/style.css' %}">
</head>
<body>

    <a href="{% url 'main:index' %}"><img id ="small_logo" src="{% static 'menu/images/small_logo.png' %}"></a>

    <div class="menu_title">
    <h1>Pizza</h1>
    </div>
    <div class="menu_list">
        {% for pizza in pizza %}
        <div class ="menu_list_item">
            <span class="menu_list_title">{{pizza.nom}}</span>
            <span class="menu_list_prix">{{pizza.prix | floatformat:2}} €</span>
            <span class="menu_list_ingredient">{{pizza.ingredient}}</span>
            {% if pizza.vegetarienne %}
                <span class="menu_list_badge">Veggies</span>
            {% endif %}
        </div>
        {% endfor %}
    </div>
</body>
</html>